version: '3'

services:
  datascience-notebook:
      build: .
      volumes:
        - ./notebooks:/home/jovyan/work/notebooks
        - ./data:/home/jovyan/work/data
      ports:
        - 8888:8888
      container_name: datascience-notebook